import type { NextPage } from "next";
import Head from "next/head";

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center min-h-screen px-4">
        <header>
          <h1 className="text-5xl md:text-[5rem] text-center leading-normal font-extrabold text-blue-300 dark:text-blue-200">
            Votista
          </h1>
        </header>
        <div>
          <h3 className="text-3xl md:text-[30px] leading-normal font-2xl text-center">
            Lorem ipsum dolor sit amet consectetur adipisicing elit
          </h3>
        </div>
        <div className="py-[2rem]">
          <div className="flex flex-col justify-center p-6 duration-500 border-2 border-blue-500 rounded hover:shadow-xl mb-4">
            <h2 className="text-xl text-gray-700 min-w-[50vw] pb-3">
              Question?
            </h2>
            <p className="text-sm text-gray-600">description</p>
            <div className="w-full flex justify-around items-center mt-3">
              <button className="text-3xl text-white w-[3rem] h-[3rem] bg-green-400 hover:bg-green-500 rounded-md items-center justify-center p-0">
                👍
              </button>
              <button className="text-3xl text-white w-[3rem] h-[3rem] bg-red-400 hover:bg-red-500 rounded-md items-center justify-center p-0">
                👎
              </button>
            </div>
          </div>
        </div>

        <footer>
          <form className="flex justify-center fixed bottom-0 right-0 left-0 p-10 border bg-white">
            <input
              name="recommend"
              type="text"
              placeholder="Do you recommend something else?"
              className="w-full px-4 py-2 mr-3 text-sm text-gray-700 border border-gray-500 rounded-lg focus:outline-none focus:border-blue-500"
            />
            <input
              type="submit"
              value="+"
              className="px-4 text-lg text-gray-100 border border-gray-900 rounded-lg focus:outline-none focus:border-blue-500 bg-blue-500 hover:bg-blue-700"
            />
          </form>
        </footer>
      </main>
    </>
  );
};

export default Home;
