import type { NextPage } from "next";
import Head from "next/head";

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Votista</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h2 className="text-5xl md:text-[5rem] text-center leading-normal font-extrabold text-blue-300 dark:text-blue-200">
          Votista
        </h2>
        <div className="flex flex-col space-y-4 ">
          <input
            type={"text"}
            placeholder={"Enter your question"}
            className={
              "w-full px-4 py-2 mr-3 text-sm text-gray-700 border border-gray-500 rounded-lg focus:outline-none focus:border-blue-500"
            }
          />
          <div className="space-x-8 md:space-x-18">
            <input
              type={"submit"}
              value={"Ask"}
              className={
                "px-4 text-2xl w-[20vw] md:w-[10rem] text-slate-100 rounded-lg focus:border-blue-500 bg-blue-400 py-1 hover:bg-blue-700 ease-in-out duration-500"
              }
            />
            <input
              type={"clear"}
              value={"Clear"}
              className={
                "px-4 text-2xl text-center  w-[20vw] md:w-[10rem] text-slate-100  rounded-lg bg-red-400 py-1 hover:bg-red-800 ease-in-out duration-500"
              }
            />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
